name: Deploy Application

on:
  push:
    branches:
      - main
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: client

      - name: Build Angular application
        run: npm run build
        working-directory: client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./client/dist/client

  server:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Start Node.js server
        run: npm start
        working-directory: server